# Generated by Django 4.2.11 on 2025-04-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='note_attachments/'),
        ),
    ]
