# Generated by Django 4.2.11 on 2025-04-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepage', '0002_note_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='attachment',
        ),
    ]
