# Generated by Django 4.2.11 on 2025-05-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepage', '0004_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
