# Generated by Django 4.2.11 on 2025-03-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
