# Generated by Django 4.2.11 on 2025-04-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_module_moduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleitem',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
