# Generated by Django 4.2.11 on 2025-04-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_user'),
        ('home', '0004_moduleitem_file_url'),
    ]

    operations = [
    ]
