# Generated by Django 4.2.11 on 2025-04-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_module_user_moduleitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
