# Generated by Django 4.2.11 on 2025-05-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='canvas_url',
            field=models.URLField(blank=True),
        ),
    ]
