# Generated by Django 4.2.11 on 2025-05-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile_canvas_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='canvas_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
