name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ################################################################
  # 1. Deploy to Production
  ################################################################
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Django App

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Dump directory tree
        run: |
          pwd
          ls -R .
#
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and collectstatic
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
        working-directory: group3_project/calendar/calendar_app

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --project stellar-nurturing
          railway up --service Group-3-spring-2025
