name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ################################################################
  # 1. Deploy to Production
  ################################################################
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Django App

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and collectstatic
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
        working-directory: group3_project/calendar

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT: stellar-nurturing
          RAILWAY_SERVICE: Group-3-spring-2025
        run: npx railway up

#          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
#        run: |
#          npx railway link --project stellar-nurturing
#          npx railway up --service Group-3-spring-2025
#RAILWAY_API_KEY: ${{ secrets.RAILWAY_TOKEN_LOGIN }}